//! Production TOML rendering for interactive and non-interactive setup.

use std::path::Path;

use super::{SetupValues, path_text, toml_string};

pub(super) fn render_config(
    values: &SetupValues,
    access_path: &Path,
    secret_path: &Path,
    hmac_path: &Path,
) -> anyhow::Result<String> {
    let endpoint = values
        .endpoint_url
        .as_ref()
        .map(|value| format!("endpoint_url = {}\n", toml_string(value)))
        .unwrap_or_default();
    let access_path = path_text(access_path)?;
    let secret_path = path_text(secret_path)?;
    let hmac_path = path_text(hmac_path)?;
    Ok(format!(
        r#"# Generated by g7mbctl setup for {:?}. Secrets are loaded from root-only files.
[server]
bind_addr = "127.0.0.1:8088"

[auth]
key_id = "g7-primary"
tenant_id = {}
hmac_secret_file = {}

[storage]
provider = {}
{}region = {}
raw_bucket = {}
derivative_bucket = {}
access_key_id_file = {}
secret_access_key_file = {}
force_path_style = {}

[database]
url = "sqlite:///var/lib/g7mediabooster/g7mb.db"
backup_directory = "/var/lib/g7mediabooster/backups"

[worker]
sandbox_binary = "/usr/local/libexec/g7mb-sandbox"
temp_directory = "/var/lib/g7mediabooster/tmp"
max_temp_disk_bytes = 12884901888

[delivery]
# Enable only after installing the provided Nginx path-only proxy.
public_enabled = false
public_bind_addr = "127.0.0.1:8089"
# HMAC protocols use distinct canonical domains. Advanced deployments may pin
# a separate root-only file before enabling this listener.
public_signing_secret_file = {}
"#,
        values.provider,
        toml_string(&values.tenant_id),
        toml_string(hmac_path),
        toml_string(values.provider.config_name()),
        endpoint,
        toml_string(&values.region),
        toml_string(&values.raw_bucket),
        toml_string(&values.derivative_bucket),
        toml_string(access_path),
        toml_string(secret_path),
        values.force_path_style,
        toml_string(hmac_path),
    ))
}
